version: "3"
services:
    feature-api:
      image: checkr/flagr
      ports: 
      - "8080:18000"
      environment:
      - "FLAGR_DB_DBDRIVER=mysql"
      - "FLAGR_DB_DBCONNECTIONSTR=flagr:dalongrong@tcp(mysql:3306)/flagr?parseTime=true"
    mysql:
      image: mysql:5.7.16
      volumes:
      - ./db/mysql:/var/lib/mysql
      ports:
      - 3306:3306
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
      - "MYSQL_ROOT_PASSWORD=dalongrong"
      - "MYSQL_DATABASE=flagr"
      - "MYSQL_USER=flagr"
      - "MYSQL_PASSWORD=dalongrong"
      - "TZ=Asia/Shanghai"
